import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "design");
const fragmentDirs = ["pages", "overlays"];
const fragments = {};

for (const dir of fragmentDirs) {
  const absDir = join(root, dir);
  const names = readdirSync(absDir).filter((name) => name.endsWith(".html")).sort();
  for (const name of names) {
    const key = `${dir}/${name}`;
    fragments[key] = readFileSync(join(absDir, name), "utf8").replace(/\r\n/g, "\n").trimEnd();
  }
}

const body = `// Generated by scripts/build_fragment_cache.mjs. Keep source fragments in pages/ and overlays/.\nwindow.NEXUS_FRAGMENTS = Object.freeze(${JSON.stringify(fragments, null, 2)});\n`;

writeFileSync(join(root, "js", "fragment-cache.js"), body, "utf8");
console.log(`Wrote ${Object.keys(fragments).length} fragments to design/js/fragment-cache.js`);
